### ISSUE TITLE
Unable to read file 'HRIR_dataset.sofa': no such file

### ISSUE THREAD

**Issue by pokjnb** [VeraE/image-source-method#1]
missing files
Any tips?

**Comment by VeraE** [comment]
In the header of [`Test_calculate_ISM.m`](https://github.com/VeraE/image-source-method/blob/master/Test_calculate_ISM.m) you can read where to find an example HRIR dataset.

**Comment by pokjnb** [comment]
OK , good news, this link is still valid!  
I will try it by following your code comments.
Thannnnks !
